production:
  solr:
    hostname: us-west-2.websolr.com
    port: 80
    path: '/solr/d740a6b006a'
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
