production:
  solr:
    hostname: index.websolr.com
    port: 80
    path: '/solr/e54b74f1f0f'
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
